plugins {
    id 'java'
    id 'io.qameta.allure' version '2.11.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

group = 'github'
version = '1.0-SNAPSHOT'

allure {
    version = '2.19.0' // версия CLI, для генерации отчета
    autoconfigure = true // автоматически подключает Allure к тестам
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.38.0'
    testImplementation 'com.codeborne:selenide:7.12.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:6.3.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.slf4j:slf4j-simple:2.0.9'
    testImplementation 'net.datafaker:datafaker:2.1.0'
}

test {
    useJUnitPlatform()
}

tasks.register('simple_test', Test) {
    useJUnitPlatform {
        includeTags 'simple'
    }
}